name: Build multiarch Open Weather Radio

on:
  push:
    branches: main
    paths:
        - 'root/**'
        - 'Dockerfile'
        - '.github/workflows/**'

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: name/app # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build and push the image
        run: |
          docker buildx build --push \
            --build-arg BUILD_FROM="ubuntu:21.04" \
            --tag jptekservices/open-weather-radio:latest \
            --tag jptekservices/open-weather-radio:0.0.4 \
            --platform linux/amd64,linux/arm64 .

