name: Build multiarch Open Weather Radio

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu:21.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
      run: |
        docker buildx build \
          --build-arg BUILD_FROM="ubuntu:21.04" \
          --tag jptekservices/open-weather-radio:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .