name: Build multiarch Open Weather Radio

on:
  push:
    branches: dev
    paths:
        - 'root/**'
        - 'Dockerfile'
        - '.github/workflows/**'
    tags:
      - "v*.*.*"

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: echo 
        run: echo ${{ env.RGITHUB_ENV }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build \
            --build-arg BUILD_FROM="ubuntu:21.04" \
            --tag jptekservices/open-weather-radio:latest \
            --tag jptekservices/open-weather-radio:${{ env.GITHUB_ENV }} \
            --platform linux/amd64,linux/arm64 .